### ISSUE TITLE
Log-in screen

### ISSUE THREAD

**Issue by AngelaLuo49021** [Covaid-co/covaid-mobile#1]
Should look something like this but covaid-ify it:
<img width="529" alt="Screen Shot 2020-05-20 at 2 28 45 PM" src="https://user-images.githubusercontent.com/42478474/82488913-618b7700-9aa6-11ea-8873-cc6f5f1d72d4.png">
* Leave room for a sign up button underneath the login button for later implementation
* Will lead to the "home" screen after successful login. 
* [Helpful Link](https://medium.com/@mmazzarolo/the-starter-app-part-2-login-screen-ui-2937e9a9083b)

**Comment by lijeffrey39** [comment]
That looks fine to me!
