### ISSUE TITLE
REFACTOR Display Requests on Home Page

### ISSUE THREAD

**Issue by AngelaLuo49021** [Covaid-co/covaid-mobile#5]
- Display pending, active, and completed requests for a volunteer. 
General Idea of how the page will be structured but put pending/active in the same display so there are actually only 2 categories:
![IMG_0031](https://user-images.githubusercontent.com/42478474/82716962-d9e96800-9c5f-11ea-83e1-21c76d2d6eb8.jpg)
How it looks on web right now:
<img width="641" alt="Screen Shot 2020-05-22 at 7 13 25 PM" src="https://user-images.githubusercontent.com/42478474/82717093-57ad7380-9c60-11ea-8a0c-3738bff260ed.png">

More functionality added in #6

**Comment by shresta4** [comment]
TODO: 

- [ ] Get pending requests to display upon landing on Requests Page

- [ ] Add badges to display # of pending/active requests (technically works but Badges are being problematic rn so commented out)
