### ISSUE TITLE
Complete a Request

### ISSUE THREAD

**Issue by AngelaLuo49021** [Covaid-co/covaid-mobile#8]
- Users should type in a description of how they completed the request 
- Afterwards, "active request" moves to the completed request display
<img width="513" alt="Screen Shot 2020-05-22 at 7 40 43 PM" src="https://user-images.githubusercontent.com/42478474/82717822-3d759480-9c64-11ea-883e-41816e63ea63.png">
- Have a thank you message display after they describe how they did it

Related to #5 and #6

**Comment by shresta4** [comment]
TODO: 
(minor fixes) 
- [x] make sure it's a minimum of 10 characters
- [x] add the example text 
- [x] Does distance work correctly ??
